Pin version 2.x of stix2 package
Version 3.0.0 introduced some breaking changes that cause
our unit tests to fail with errors like this:

    Traceback (most recent call last):
      File "/__w/threatbus/threatbus/plugins/apps/threatbus_misp/threatbus_misp/test_message_mapping.py", line 174, in test_valid_stix_sighting
        misp_sighting = stix2_sighting_to_misp(self.sighting)
      File "/__w/threatbus/threatbus/plugins/apps/threatbus_misp/threatbus_misp/message_mapping.py", line 329, in stix2_sighting_to_misp
        if "x_threatbus_source" in sighting.object_properties():
      File "/usr/local/lib/python3.9/dist-packages/stix2/base.py", line 269, in __getattr__
        raise AttributeError(
    AttributeError: 'Sighting' object has no attribute 'object_properties'